CREATE TABLE [dbo].[AggrManagementMetrics] (
    [YearNum]                          INT              NOT NULL,
    [WeekNum]                          INT              NOT NULL,
    [WeekName]                         VARCHAR (15)     NOT NULL,
    [Rabota_NewResumeCnt]              INT              NULL,
    [Work_NewResumeCnt]                INT              NULL,
    [Rabota_NewVacancyCnt]             INT              NULL,
    [Work_NewVacancyCnt]               INT              NULL,
    [Rabota_AvgVacancyCnt]             INT              NULL,
    [Work_AvgVacancyCnt]               INT              NULL,
    [Rabota_SumRecognizedRevenue]      DECIMAL (18, 2)  NULL,
    [Rabota_ResponsesCnt]              INT              NULL,
    [Work_ResponsesCnt]                INT              NULL,
    [Rabota_ResponsersNum]             INT              NULL,
    [Rabota_NewEmails]                 INT              NULL,
    [Rabota_GreenWeightTotal]          DECIMAL (4, 1)   NULL,
    [Rabota_GreenWeightSF]             DECIMAL (4, 1)   NULL,
    [Rabota_GreenWeightSMB]            DECIMAL (4, 1)   NULL,
    [Rabota_StarsGreenWeightTotal]     DECIMAL (4, 1)   NULL,
    [Rabota_StarsGreenWeightSF]        DECIMAL (4, 1)   NULL,
    [Rabota_StarsGreenWeightSMB]       DECIMAL (4, 1)   NULL,
    [Rabota_ResponsesCnt_Viewed]       INT              NULL,
    [OpenedContacts_Count]             INT              NULL,
    [OpenedContacts_NotebookCount]     INT              NULL,
    [Rabota_ResponsesCnt_Viewed_Popup] INT              NULL,
    [Rabota_ResponsesCnt_Viewed_Bulk]  INT              NULL,
    [Rabota_PaidPublicationsWeight]    DECIMAL (18, 15) NULL,
    [Rabota_ResponsesCnt_Desktop]      INT              NULL,
    [Rabota_ResponsesCnt_Mobile]       INT              NULL,
    [AvgResponsesHot_Kiev]             DECIMAL (5, 2)   NULL,
    [AvgResponsesHot_NotKiev]          DECIMAL (5, 2)   NULL,
    [AvgResponsesBasic_Kiev]           DECIMAL (5, 2)   NULL,
    [AvgResponsesBasic_NotKiev]        DECIMAL (5, 2)   NULL,
    [AvgResponsesOptiprof_Kiev]        DECIMAL (5, 2)   NULL,
    [AvgResponsesOptiprof_NotKiev]     DECIMAL (5, 2)   NULL,
    CONSTRAINT [PK_AggrManagementMetrics] PRIMARY KEY CLUSTERED ([YearNum] ASC, [WeekNum] ASC, [WeekName] ASC)
);

